version: '3.8'

services:
  api-docs:
    image: swaggerapi/swagger-ui:v3.38.0
    volumes:
      - ./:/apidocs/
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/apidocs/swagger-config.yaml
