openapi: "3.0.0"

info:
  description: "Template description"
  version: "0.0.1"
  title: "Google Map API"

servers:
  - url: https://maps.googleapis.com/maps/api
    description: Google Map's API

tags:
  - name: "Google Map Root resource"

paths:
  /:
    get:
      tags: 
        - "Google Map Root resource"
      responses:
        200:
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/payload'

components:
  schemas:
    payload:
      type: object
            

